### ISSUE TITLE
Integrating CometChat library in React native iOS application issues

### ISSUE THREAD

**Issue by zainebzaineb** [cometchat/cometchat-sample-app-react-native#37]
Hi,
I am integrating CometChat library in React native application. So I have two issues: 

The first, when I click on the call button the calling interface is not displayed but when I click on the back button it is displayed.
The second, when I click on the Video Library button then I choose my video finally the app is crashing.
Please guide me how can I integrate Call  and  Video Library Feature.

https://user-images.githubusercontent.com/36507391/122204672-4d779c00-ce97-11eb-89b7-a83174abbff3.mp4

Thanks in advance

Version used:
React Native Version: 0.64.0
CometChat Version:  ^2.3.3
CometChat Call Version: 2.0.3-beta1

**Comment by Burhan-Arbisoft** [comment]
I am also having this same issue..
Anyone else having this issue and have fixed this as well ?

**Comment by TirathBhuva** [comment]
Hey guys, 
     Whenever a user clicks on the video call or an audio call and we pass that event down to `CometChatConversationList` or `CometChatGroupList` or `CometChatUserList` and from there we open a modal on which we display incoming calls and outgoing calls. Due to some reason on IOS, we are not able to open the modal from a parent stack. So the best solution is to integrate the  `CometChatIncomingCall`, `CometChatOutgoingCall`, `CometChatOutgoingDirectCall`, `CometChatIncomingDirectCall`,  components in the `CometChatMessage` Component. You can refer to `CometChatConversationListWithMessage` Component as these components are integrated in `CometChatConversationListWithMessage` Component.
